[mysql]
name = "books_shop"
host = "127.0.0.1"
post = "30306"
password = "My:S3cr3t/"

[redis]
address = "localhost:6379"
password = ""
db = 0
key = "top_books"

[elasticsearch]
url = "http://localhost:9200"
indext = "bookshop"